import {Expression} from "../../../language/expressions/expression";
import {CodeWriter} from "../codeWriter";
import {LexyCodeConstants} from "../lexyCodeConstants";
import {ExtractFunctionStatement} from "./extractFunctionStatement";
import {Assert} from "../../../infrastructure/assert";
import {
  instanceOfSpreadAssignmentExpression,
  SpreadAssignmentExpression
} from "../../../language/expressions/spreadAssignmentExpression";

//A lexy function is with a spread operator (at statement level) which means it should auto map it's results
//Otherwise LexyFunctionCallExpression's syntax is generated by lexyFunctionCall
//Syntax: "... = LexyFunction()"
export class AutoMapLexyFunctionStatement {

  public static matches(expression: Expression): boolean {
    return instanceOfSpreadAssignmentExpression(expression);
  }

  public static render(expression: SpreadAssignmentExpression, codeWriter: CodeWriter) {

    Assert.notNull(expression, "functionCallExpression");

    let resultsVariable = `${LexyCodeConstants.resultsVariable}_${codeWriter.currentLine}`;

    AutoMapLexyFunctionStatement.renderRunFunction(expression, resultsVariable, codeWriter);

    ExtractFunctionStatement.renderExtract(
      Assert.notNull(expression.mapping, "expression.mapping"),
      resultsVariable, codeWriter);
  }

  private static renderRunFunction(expression: SpreadAssignmentExpression,
                                   resultsVariable: string,
                                   codeWriter: CodeWriter) {

    codeWriter.startLine(`let ${resultsVariable} = `);
    codeWriter.renderExpression(expression.assignment);
    codeWriter.endLine(`;`);
  }
}
