import {Expression} from "../../../language/expressions/expression";
import {CodeWriter} from "../codeWriter";
import {LexyCodeConstants} from "../lexyCodeConstants";
import {LexyFunctionCall} from "../functionCalls/lexyFunctionCall";
import {
  instanceOfLexyFunctionCallExpression,
  LexyFunctionCallExpression
} from "../../../language/expressions/functions/lexyFunctionCallExpression";
import {FillFunctionStatement} from "./fillFunctionStatement";
import {ExtractFunctionStatement} from "./extractFunctionStatement";

//A lexy function is called without assignment (at statement level) which means it should auto map it's results and parameters
//Otherwise LexyFunctionCallExpression's syntax is generated by lexyFunctionCall
//Syntax: "LexyFunction()"
export class AutoMapLexyFunctionStatement {

  public static matches(expression: Expression): boolean {
    if (!instanceOfLexyFunctionCallExpression(expression)) return false;
    if (!expression.autoMap) {
      throw new Error("AutoMap should be set to true for a statement.");
    }
    return true;
  }

  public static render(functionCallExpression: LexyFunctionCallExpression, codeWriter: CodeWriter) {

    let parameterVariable = `${LexyCodeConstants.parameterVariable}_${codeWriter.currentLine}`;
    let resultsVariable = `${LexyCodeConstants.resultsVariable}_${codeWriter.currentLine}`;

    FillFunctionStatement.renderFill(
      parameterVariable,
      functionCallExpression.functionParametersType,
      functionCallExpression.mappingParameters,
      codeWriter);

    AutoMapLexyFunctionStatement.renderRunFunction(functionCallExpression, parameterVariable, resultsVariable, codeWriter);

    ExtractFunctionStatement.renderExtract(
      functionCallExpression.mappingResults,
      resultsVariable,
      codeWriter);
  }

  private static renderRunFunction(lexyFunction: LexyFunctionCallExpression,
                            parameterVariable: string,
                            resultsVariable: string,
                            codeWriter: CodeWriter) {
    codeWriter.startLine(`let ${resultsVariable} = `);
    LexyFunctionCall.renderFunction(lexyFunction.functionName, parameterVariable, codeWriter);
    codeWriter.endLine(";");
  }
}
