import {Expression} from "../../../language/expressions/expression";
import {CodeWriter} from "../codeWriter";
import {LexyCodeConstants} from "../lexyCodeConstants";
import {
  asLexyFunctionCallExpression,
  LexyFunctionCallExpression
} from "../../../language/expressions/functions/lexyFunctionCallExpression";
import {FillFunctionStatement} from "./fillFunctionStatement";
import {ExtractFunctionStatement} from "./extractFunctionStatement";
import {Assert} from "../../../infrastructure/assert";
import {
  asAutoMapLexyFunctionCall,
  AutoMapLexyFunctionCall,
  instanceOfAutoMapLexyFunctionCall
} from "../../../language/expressions/functions/autoMapLexyFunctionCallExpression";
import {functionClassName} from "../classNames";

//A lexy function is called without assignment (at statement level) which means it should auto map it's results and parameters
//Otherwise LexyFunctionCallExpression's syntax is generated by lexyFunctionCall
//Syntax: "LexyFunction()"
export class AutoMapLexyFunctionStatement {

  public static matches(expression: Expression): boolean {
    const lexyFunctionCallExpression = asLexyFunctionCallExpression(expression);
    if (lexyFunctionCallExpression == null) return false;
    return instanceOfAutoMapLexyFunctionCall(lexyFunctionCallExpression.functionCall);
  }

  public static render(expression: LexyFunctionCallExpression, codeWriter: CodeWriter) {

    Assert.notNull(expression, "functionCallExpression");

    let functionCall = Assert.is<AutoMapLexyFunctionCall>(asAutoMapLexyFunctionCall, expression.functionCall, "expression.FunctionCall");
    let parameterVariable = `${LexyCodeConstants.parameterVariable}_${codeWriter.currentLine}`;
    let resultsVariable = `${LexyCodeConstants.resultsVariable}_${codeWriter.currentLine}`;

    FillFunctionStatement.renderFill(
      parameterVariable,
      functionCall.parametersTypes,
      functionCall.mappingParameters,
      codeWriter);

    AutoMapLexyFunctionStatement.renderRunFunction(expression, parameterVariable, resultsVariable, codeWriter);

    ExtractFunctionStatement.renderExtract(
      functionCall.mappingResults,
      resultsVariable,
      codeWriter);
  }

  private static renderRunFunction(expression: LexyFunctionCallExpression,
                                   parameterVariable: string,
                                   resultsVariable: string,
                                   codeWriter: CodeWriter) {
    codeWriter.startLine(`let ${resultsVariable} = `);
    codeWriter.writeEnvironment("." + functionClassName(expression.functionName));
    codeWriter.write(`(${parameterVariable}, ${LexyCodeConstants.contextVariable})`);
    codeWriter.endLine(";");
  }
}
