export enum TokenType {
  BooleanLiteralToken = 'BooleanLiteralToken',
  BuildLiteralToken = 'BuildLiteralToken',
  BuildCommentOrDivisionToken = 'BuildCommentOrDivisionToken',
  CommentToken = 'CommentToken',
  DateTimeLiteralToken = 'DateTimeLiteralToken',
  KeywordToken = 'KeywordToken',
  MemberAccessLiteralToken = 'MemberAccessLiteralToken',
  NumberLiteralToken = 'NumberLiteralToken',
  OperatorToken = 'OperatorToken',
  QuotedLiteralToken = 'QuotedLiteralToken',
  StringLiteralToken = 'StringLiteralToken',
  TableSeparatorToken = 'TableSeparatorToken',
  WhitespaceToken = 'WhitespaceToken',
}